import {$,$$,state,loadPrefs,loadSavedData,clearSavedData,icon,text,esc,savePrefs} from './core.js';
import {settingsMarkup,initThemeUI,applyTheme} from './theme.js';
import {searchOverlayMarkup,initSearch,bindRenderedSearch,terms,resetSearch} from './search.js';
import {L,home,collection,helpMarkup,dataControlsMarkup,bindCommon,initHelp,initDataIO,section} from './ui.js';
import {toolbarMarkup,initToolbar,captureSectionDefaults} from './toolbar.js';
import {mountCollectionSearch} from './collection-search.js';
import {qrMarkup,initQr,openQr} from './qr.js';
import {editorialPage} from './pages.js';
import {recipeDetailV4,ingredientDetailV4,trialDetail,bindRecipeDetailTools} from './detail.js';
import {mergeEquipmentCatalog,equipmentDetail} from './equipment.js';
import {initFloatingSystem} from './floating.js';
import {initContextTheme,refreshContextTheme} from './context-theme.js';
import {initResponsiveNav,refreshResponsiveNav} from './responsive-nav.js';
import {LANGUAGES,alternateLanguageOptions,languageDirection,uiLabel} from './i18n.js';

const SITE_VERSION='V1 RC1.2 FR';
const SITE_UPDATED_AT='2026-08-26 18:15 Europe/Paris';

function mergeCatalog(d,catalog){if(!catalog)return d;d.recipes=d.recipes||[];const ids=new Set(d.recipes.map(x=>x.id));for(const r of catalog.recipes||[]){if(!ids.has(r.id)){d.recipes.push(r);ids.add(r.id)}}return d}
async function loadDefault(force=false){
  let d=!force?loadSavedData():null;
  const [mainR,trialsR,catalogR,equipmentR,equipmentCatchupR]=await Promise.all([
    d?Promise.resolve(null):fetch('./data/demo.json',{cache:'no-store'}),
    fetch('./data/trials.json',{cache:'no-store'}).catch(()=>null),
    fetch('./data/catalog-v1.json',{cache:'no-store'}).catch(()=>null),
    fetch('./data/equipment-v1.json',{cache:'no-store'}).catch(()=>null),
    fetch('./data/equipment-catchup-v1.json',{cache:'no-store'}).catch(()=>null)
  ]);
  if(!d){if(!mainR?.ok)throw new Error(`data ${mainR?.status||'unavailable'}`);d=await mainR.json()}
  if(catalogR?.ok)d=mergeCatalog(d,await catalogR.json());
  if(equipmentR?.ok)d=mergeEquipmentCatalog(d,await equipmentR.json());
  if(equipmentCatchupR?.ok)d=mergeEquipmentCatalog(d,await equipmentCatchupR.json());
  if(trialsR?.ok){d.trials=await trialsR.json();d.trials.forEach(t=>{const r=d.recipes?.find(x=>x.id===t.recipe_id);if(r){r.trials=r.trials||[];if(!r.trials.includes(t.id))r.trials.push(t.id)}})}else d.trials=d.trials||[];
  if(force)clearSavedData();return d
}
function navMarkup(){return `<nav id="mainNav" class="nav" aria-label="Navigation"><button class="btn" data-section="home">Accueil</button><button class="btn" data-section="recipes">Recettes</button><button class="btn" data-section="ingredients">Ingrédients</button><button class="btn" data-section="techniques">Techniques & astuces</button><button class="btn" data-section="equipment">Matériel</button><button class="btn" data-section="library">Bibliothèque</button><button class="btn" data-section="concept">Concept</button></nav>`}
function languageMarkup(){return `<div id="langSwitch" class="lang-switch french-first" dir="ltr"><button class="btn lang-source-btn" id="sourceLanguage" title="Français · langue source"><span class="lang-master-dot" aria-hidden="true"></span><span>🇫🇷</span><span>FR</span></button><label class="alternate-language" title="Choisir la langue de traduction"><span class="sr-only">Langue de traduction</span><select id="alternateLanguage" aria-label="Langue de traduction">${alternateLanguageOptions()}</select></label></div>`}
function shell(){document.body.innerHTML=`<header id="siteHeader" class="site-header"><div class="wrap"><div class="topbar"><div class="brand" id="brandHome"><span id="brandLogo" class="brand-logo brand-logo-emoji">🍽️</span><span>CuisineX</span><span class="badge" title="Version du site">${SITE_VERSION}</span><span class="muted" style="font-size:.8rem" title="Dernière mise à jour du site">MAJ ${SITE_UPDATED_AT}</span></div><span class="grow"></span>${languageMarkup()}<button class="icon-btn" id="openHelpHeader" title="Aide contextuelle">${icon('help')}</button><button class="icon-btn" id="openSettings" title="Paramètres">${icon('gear')}</button></div>${navMarkup()}</div></header><main id="app" class="wrap"></main>${searchOverlayMarkup()}${settingsMarkup()}${helpMarkup()}${toolbarMarkup()}${qrMarkup()}<footer id="siteFooter" class="wrap"><p class="muted" style="font-size:.8rem">CuisineX ${SITE_VERSION} · mise à jour ${SITE_UPDATED_AT}</p></footer>`}
function localizedNav(){const map={home:L('home'),recipes:L('recipes'),ingredients:L('ingredients'),techniques:L('techniques'),equipment:L('equipment'),library:L('library'),concept:uiLabel(state.lang,'concept')};$$('[data-section]').forEach(b=>{b.textContent=map[b.dataset.section]||b.dataset.section;b.classList.toggle('active',b.dataset.section===state.section)});$('#sourceLanguage')?.classList.toggle('active',state.lang==='fr');const alt=$('#alternateLanguage');if(alt){if(state.lang!=='fr')alt.value=state.lang;else alt.value=state.prefs.secondaryLanguage||'en';alt.classList.toggle('active',state.lang!=='fr')}document.documentElement.lang=state.lang;document.documentElement.dir=languageDirection(state.lang);document.body.classList.toggle('rtl',languageDirection(state.lang)==='rtl')}
function globalSearchView(){const ts=terms();if(!ts.length||state.searchContext!=='global')return null;const groups=['recipes','ingredients','techniques','equipment','library'].filter(t=>state.prefs.searchScopes.includes(t));return `<div class="panel search-results-head"><h1>${L('search')}</h1><p class="muted">${ts.map(t=>`#${esc(t)}`).join(' · ')}</p><button class="btn" data-nav="home">← ${L('home')}</button></div>${groups.map(t=>`<section id="search-${t}" class="section"><div class="section-head"><h2>${({recipes:L('recipes'),ingredients:L('ingredients'),techniques:L('techniques'),equipment:L('equipment'),library:L('library')})[t]}</h2></div><div class="section-body">${collection(t)}</div></section>`).join('')}`}
function genericDetail(x){return `<button class="btn no-print" id="backToList">← ${L('back')}</button><div class="panel detail-head"><div>${x.status?`<button class="badge clickable ${x.status==='canonical'?'ok':'warn'}" data-status-filter="${esc(x.status)}">${esc(x.status)}</button>`:''}<span class="badge">${esc(x.id)}</span><h1>${esc(text(x.title||x.name))}</h1><p>${esc(text(x.summary||x.notes)||'')}</p></div><div class="detail-actions">${x.url?`<a class="btn" href="${esc(x.url)}" target="_blank" rel="noopener">Ouvrir ${icon('external')}</a>`:''}<button class="btn" data-open-qr>${icon('qr')} QR</button></div></div>${x.tags?section(`generic-${x.id}-tags`,'Tags',x.tags.map(t=>`<span class="badge">#${esc(t)}</span>`).join(' '),{open:false}):''}`}
function syncUrl(){const u=new URL(location.href);['section','type','id','lang','q'].forEach(k=>u.searchParams.delete(k));u.searchParams.set('lang',state.lang);if(state.detail){u.searchParams.set('type',state.detail.type);u.searchParams.set('id',state.detail.id)}else u.searchParams.set('section',state.section);if(state.query)u.searchParams.set('q',state.query);history.replaceState(null,'',u)}
function restoreFromUrl(){const p=new URLSearchParams(location.search),lang=p.get('lang'),type=p.get('type'),id=p.get('id'),sectionId=p.get('section'),q=p.get('q');if(lang&&LANGUAGES[lang]&&(lang==='fr'||state.prefs.languages?.[lang]!==false))state.lang=lang;if(type&&id)state.detail={type,id},state.section=type;else if(sectionId)state.section=sectionId;if(q){state.query=q;state.searchContext='global'}}
export function render(){localizedNav();applyTheme();const app=$('#app'),global=globalSearchView();if(global&&!state.detail)app.innerHTML=global;else if(state.detail){const {type,id}=state.detail,x=(state.data?.[type]||[]).find(o=>o.id===id);if(!x)app.innerHTML='<div class="panel">Objet introuvable.</div>';else if(type==='recipes')app.innerHTML=recipeDetailV4(x);else if(type==='ingredients')app.innerHTML=ingredientDetailV4(x);else if(type==='equipment')app.innerHTML=equipmentDetail(x);else if(type==='trials')app.innerHTML=trialDetail(x);else app.innerHTML=genericDetail(x)}else if(state.section==='home')app.innerHTML=home()+section('home-data','Données du prototype',dataControlsMarkup(),{open:false,helpShort:'Import/export local du JSON de démonstration.'});else if(state.section==='concept'||state.section==='legal')app.innerHTML=editorialPage(state.section);else app.innerHTML=`<div class="panel collection-heading"><h1>${({recipes:L('recipes'),ingredients:L('ingredients'),techniques:L('techniques'),equipment:L('equipment'),library:L('library')})[state.section]}</h1><p class="muted">Recherche, filtres, vues et pagination utilisent les mêmes composants partagés.</p></div>${collection(state.section)}`;bindCommon(render);bindRenderedSearch();mountCollectionSearch(render);initDataIO(loadDefault,render);bindShellEvents();bindRecipeDetailTools();captureSectionDefaults();syncUrl();refreshContextTheme();refreshResponsiveNav()}
function setLanguage(lang){if(!LANGUAGES[lang]||(lang!=='fr'&&state.prefs.languages?.[lang]===false))return;state.lang=lang;if(lang!=='fr')state.prefs.secondaryLanguage=lang;savePrefs();render()}
function bindShellEvents(){$$('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;state.detail=null;state.page=1;state.searchContext='section';resetSearch({renderEvent:false});render()});$('#sourceLanguage')?.addEventListener('click',()=>setLanguage('fr'));$('#alternateLanguage')?.addEventListener('change',e=>setLanguage(e.target.value));$('#brandHome').onclick=()=>{state.section='home';state.detail=null;state.searchContext='section';resetSearch({renderEvent:false});render()};$$('[data-footer-nav]').forEach(a=>a.onclick=e=>{e.preventDefault();state.section=a.dataset.footerNav;state.detail=null;state.searchContext='section';resetSearch({renderEvent:false});render();scrollTo({top:0,behavior:'smooth'})})}
function restoreSearchFocus(){const selector=state.searchContext==='section'?'#collectionSearchInput':'[data-search-input][data-search-context="global"]',input=$(selector);if(!input)return;input.focus({preventScroll:true});const n=input.value.length;try{input.setSelectionRange(n,n)}catch{}}
async function init(){loadPrefs();state.data=await loadDefault();restoreFromUrl();shell();initFloatingSystem();initResponsiveNav();initSearch();initThemeUI();initContextTheme();initHelp();initToolbar();initQr();document.addEventListener('cuisinex:search-change',()=>{const keepFocus=document.activeElement?.matches?.('[data-search-input]');state.page=1;render();if(keepFocus)requestAnimationFrame(restoreSearchFocus)});document.addEventListener('cuisinex:open',e=>{state.detail=e.detail;state.section=e.detail.type;state.page=1;state.searchContext='section';render();scrollTo({top:0,behavior:'smooth'})});document.addEventListener('cuisinex:open-qr',openQr);render()}
init().catch(err=>{document.body.innerHTML=`<pre style="padding:20px">CuisineX preview error: ${String(err)}</pre>`})
