import {$,$$,state,normalize,text,savePrefs,allObjects,toast,icon} from './core.js';
import {openFloating,closeFloating} from './floating.js';

const scopeLabels={recipes:'Recettes',ingredients:'Ingrédients',techniques:'Techniques',equipment:'Matériel',library:'Bibliothèque'};

export function homeSearchMarkup(){return `<div class="home-search-module"><div class="home-search-title"><div><strong>Recherche globale</strong><span class="muted">Recettes, ingrédients, techniques, matériel et bibliothèque.</span></div><button class="icon-btn" data-home-search-config title="Configurer la recherche">${icon('sliders')}</button></div><div class="home-search-row"><input data-search-input data-search-context="global" type="search" placeholder="Ex. chocolat, crème, tempérage…" autocomplete="off"><button class="btn primary" data-home-search-submit>${icon('search')} Rechercher</button><button class="icon-btn" data-home-search-reset title="Réinitialiser">${icon('reset')}</button></div><div data-home-token-row class="token-row home-token-row hidden"></div></div>`}
export function searchOverlayMarkup(){return `<aside id="searchConfigPanel" class="search-config-float" data-floating-key="search" aria-hidden="true"><div class="floating-head search-config-head"><strong>🔎 Configuration de la recherche</strong><span class="badge" id="searchContextLabel">Globale</span></div><div class="floating-body"><div id="tokenRow" class="token-row hidden"></div><div class="field"><strong>Mode de saisie</strong><div class="filter-row"><button class="btn" data-search-mode="free">Libre</button><button class="btn" data-search-mode="suggest">Suggestions</button><button class="btn" data-search-mode="tokens">Jetons</button></div></div><div class="field"><strong>Opérateur</strong><div class="filter-row"><button class="btn" data-search-op="and">ET</button><button class="btn" data-search-op="or">OU</button></div></div><div id="scopeConfigGroup" class="field"><strong>Sections recherchées</strong><div class="filter-row">${Object.entries(scopeLabels).map(([k,l])=>`<button class="btn" data-search-scope="${k}">${l}</button>`).join('')}</div></div><div id="suggestions" class="suggestions muted"></div><div class="filter-row search-config-actions"><button class="btn" id="searchConfigReset">${icon('reset')} Réinitialiser la recherche</button></div></div></aside>`}
export function openSearchConfig(context='global'){state.searchContext=context;const label=$('#searchContextLabel');if(label)label.textContent=context==='global'?'Globale':`Dans ${scopeLabels[state.section]||state.section}`;$('#scopeConfigGroup')?.classList.toggle('hidden',context!=='global');openFloating('search');syncButtons();renderTokens();updateSuggestions()}
function syncButtons(){$$('[data-search-mode]').forEach(b=>b.classList.toggle('active',b.dataset.searchMode===state.prefs.searchMode));$$('[data-search-op]').forEach(b=>b.classList.toggle('active',b.dataset.searchOp===state.prefs.searchOperator));$$('[data-search-scope]').forEach(b=>b.classList.toggle('active',state.prefs.searchScopes.includes(b.dataset.searchScope)));$('#tokenRow')?.classList.toggle('hidden',state.prefs.searchMode!=='tokens');$$('[data-home-token-row]').forEach(r=>r.classList.toggle('hidden',state.prefs.searchMode!=='tokens'))}
function parseTokens(raw){return raw.trim().split(/[\s,;]+/).map(x=>x.trim()).filter(x=>x.length>1)}
function tokenHtml(){return state.tokens.map((t,i)=>`<span class="token">${t}<button data-token-remove="${i}" aria-label="Supprimer ${t}">×</button></span>`).join('')}
function renderTokens(){const html=tokenHtml();$$('#tokenRow,[data-home-token-row]').forEach(row=>{row.innerHTML=html;$$('[data-token-remove]',row).forEach(b=>b.onclick=()=>{state.tokens.splice(Number(b.dataset.tokenRemove),1);renderTokens();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))})})}
export function terms(){if(state.prefs.searchMode==='tokens')return state.tokens.map(normalize);return parseTokens(state.query).map(normalize)}
export function matchesObject(obj){const ts=terms();if(!ts.length)return true;const h=normalize(JSON.stringify(obj));return state.prefs.searchOperator==='or'?ts.some(t=>h.includes(t)):ts.every(t=>h.includes(t))}
export function filteredObjects(type){let pool=[];if(type){pool=(state.data?.[type]||[]).map(x=>({...x,__type:type}))}else{pool=allObjects().filter(x=>state.prefs.searchScopes.includes(x.__type))}pool=pool.filter(matchesObject);if(type==='recipes'){if(Array.isArray(state.recipeStatusFilters))pool=pool.filter(x=>state.recipeStatusFilters.includes(x.status||'sans_statut'));else if(state.statusFilter)pool=pool.filter(x=>x.status===state.statusFilter)}return pool}
function updateSuggestions(){const box=$('#suggestions');if(!box)return;if(state.prefs.searchMode!=='suggest'||state.query.trim().length<1){box.innerHTML='';return}const q=normalize(state.query.split(/\s+/).at(-1)),values=new Set();allObjects().forEach(o=>{[text(o.title),text(o.name),...(o.tags||[])].filter(Boolean).forEach(v=>{if(normalize(v).includes(q))values.add(v)})});box.innerHTML=[...values].slice(0,10).map(v=>`<button class="chip-btn" data-suggestion="${String(v).replace(/"/g,'&quot;')}">${v}</button>`).join(' ');$$('[data-suggestion]',box).forEach(b=>b.onclick=()=>{const parts=state.query.trim().split(/\s+/);parts[parts.length-1]=b.dataset.suggestion;state.query=parts.join(' ');syncSearchInputs();updateSuggestions();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))})}
export function syncSearchInputs(){$$('[data-search-input]').forEach(i=>{if(i&&document.activeElement!==i)i.value=state.query})}
export function resetSearch({renderEvent=true}={}){state.query='';state.tokens=[];state.statusFilter=null;state.recipeStatusFilters=null;state.page=1;syncSearchInputs();renderTokens();updateSuggestions();if(renderEvent)document.dispatchEvent(new CustomEvent('cuisinex:search-change'))}
function commitTokens(value,context){const add=parseTokens(value);for(const t of add)if(!state.tokens.includes(t))state.tokens.push(t);state.query='';state.searchContext=context;renderTokens();syncSearchInputs();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))}
export function bindSearchInput(input,context='global'){if(!input||input.dataset.searchBound)return;input.dataset.searchBound='true';input.value=state.query;input.addEventListener('input',()=>{state.searchContext=context;state.query=input.value;if(state.prefs.searchMode!=='tokens'){state.page=1;updateSuggestions();syncSearchInputs();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))}});input.addEventListener('keydown',e=>{if(state.prefs.searchMode==='tokens'&&(e.key==='Enter'||e.key===',')){e.preventDefault();commitTokens(input.value,context);input.value=''}})}
export function bindRenderedSearch(){$$('[data-search-input]').forEach(input=>bindSearchInput(input,input.dataset.searchContext||'global'));$$('[data-home-search-config]').forEach(b=>b.onclick=()=>openSearchConfig('global'));$$('[data-home-search-reset]').forEach(b=>b.onclick=()=>resetSearch());$$('[data-home-search-submit]').forEach(b=>b.onclick=()=>{state.searchContext='global';document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});syncSearchInputs();renderTokens()}
export function initSearch(){syncButtons();bindRenderedSearch();$('#searchConfigReset')?.addEventListener('click',()=>resetSearch());$$('[data-search-mode]').forEach(b=>b.onclick=()=>{state.prefs.searchMode=b.dataset.searchMode;savePrefs();syncButtons();updateSuggestions();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});$$('[data-search-op]').forEach(b=>b.onclick=()=>{state.prefs.searchOperator=b.dataset.searchOp;savePrefs();syncButtons();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});$$('[data-search-scope]').forEach(b=>b.onclick=()=>{const k=b.dataset.searchScope,a=state.prefs.searchScopes;state.prefs.searchScopes=a.includes(k)?a.filter(x=>x!==k):[...a,k];if(!state.prefs.searchScopes.length){state.prefs.searchScopes=[k];toast('Au moins une section doit rester active')}savePrefs();syncButtons();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFloating('search')})}
